/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,jsx}"],
  theme: {
    extend: {
      colors: {
        surface: "#f8f9ff",
        "surface-dim": "#ccdbf3",
        "surface-bright": "#f8f9ff",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#eff4ff",
        "surface-container": "#e6eeff",
        "surface-container-high": "#dce9ff",
        "surface-container-highest": "#d5e3fc",
        "on-surface": "#0d1c2e",
        "on-surface-variant": "#434652",
        "inverse-surface": "#233144",
        "inverse-on-surface": "#eaf1ff",
        outline: "#747783",
        "outline-variant": "#c4c6d4",
        "surface-tint": "#325ab4",
        primary: "#002f7b",
        "on-primary": "#ffffff",
        "primary-container": "#17459f",
        "on-primary-container": "#a1b9ff",
        "inverse-primary": "#b2c5ff",
        secondary: "#745b00",
        "on-secondary": "#ffffff",
        "secondary-container": "#fecb00",
        "on-secondary-container": "#6e5700",
        tertiary: "#323435",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#494b4b",
        "on-tertiary-container": "#babbbb",
        error: "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        "primary-fixed": "#dae2ff",
        "primary-fixed-dim": "#b2c5ff",
        "on-primary-fixed": "#001848",
        "on-primary-fixed-variant": "#10419b",
        "secondary-fixed": "#ffe08b",
        "secondary-fixed-dim": "#f1c100",
        "on-secondary-fixed": "#241a00",
        "on-secondary-fixed-variant": "#584400",
        "tertiary-fixed": "#e2e2e2",
        "tertiary-fixed-dim": "#c6c6c7",
        "on-tertiary-fixed": "#1a1c1c",
        "on-tertiary-fixed-variant": "#454747",
        background: "#f8f9ff",
        "on-background": "#0d1c2e",
        "surface-variant": "#d5e3fc",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        base: "8px",
        "margin-desktop": "32px",
        "container-max": "1440px",
        "sidebar-width": "260px",
        gutter: "24px",
        "margin-mobile": "16px",
      },
      fontFamily: {
        sans: ["Geist", "sans-serif"],
      },
      fontSize: {
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "headline-lg-mobile": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "body-sm": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "headline-sm": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "600" }],
        "headline-md": ["24px", { lineHeight: "32px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "label-md": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "600" }],
      },
      boxShadow: {
        card: "0px 4px 12px rgba(23, 69, 159, 0.05)",
        panel: "0px 12px 32px rgba(0, 0, 0, 0.1)",
      },
    },
  },
  plugins: [],
};
